import cv2 as cv
import numpy as np

img = cv.imread('photos/cat1.jpg')
cv.imshow('Cat', img)

blank = np.zeros(img.shape, dtype='uint8') # create a blank image with the same shape as the original image, the dtype parameter is used to specify the data type of the pixel values in the blank image. In this example, we will set the data type to uint8, which means that the pixel values in the blank image will be 8-bit unsigned integers, which can represent values from 0 to 255. The blank image will be used to draw the contours on it, so that we can visualize the contours without modifying the original image.
cv.imshow('Blank', blank)

gray = cv.cvtColor(img, cv.COLOR_BGR2GRAY) # convert the image to grayscale, the first parameter is the input image, and the second parameter is the color conversion code, which is used to specify how the color space of the image will be converted. In this example, we will convert the image from BGR color space to grayscale color space by setting the color conversion code to COLOR_BGR2GRAY.
cv.imshow('Gray', gray)

blur = cv.GaussianBlur(gray, (5, 5), cv.BORDER_DEFAULT) # apply a Gaussian blur to the grayscale image to reduce noise, the first parameter is the input image, the second parameter is the kernel size, which is used to specify the size of the Gaussian kernel that will be applied to the image. In this example, we will set the kernel size to (5, 5), which means that we will use a 5x5 Gaussian kernel to blur the image. The third parameter is the border type, which is used to specify how the borders of the image will be handled when applying the Gaussian blur. In this example, we will setthe border type to BORDER_DEFAULT, which means thatthe borders ofthe image will be handled usingthe default border handling method.
# cv.imshow('Blur', blur)
    
canny = cv.Canny(blur, 150, 175) # apply the Canny edge detection algorithm to the blurred image, the first parameter is the input image, the second parameter is the lower threshold for the hysteresis procedure, and the third parameter is the upper threshold for the hysteresis procedure. In this example, we will set the lower threshold to 150 and the upper threshold to 175, which will give us a good result for edge detection. The Canny edge detection algorithm works by first applying a Gaussian blur to the image to reduce noise,
# then it applies the Sobel operator to calculate the gradient of the image, and finally it applies the hysteresis procedure to determine which edges are strong and which edges are weak. The Canny edge detection algorithm is a multi-stage algorithm that is used to detect edges in an image, and it is a popular choice for edge detection because it produces good results and is relatively fast.
cv.imshow('Canny', canny)

ret, thresh = cv.threshold(gray, 125, 255, cv.THRESH_BINARY) # apply a binary threshold to the grayscale image to create a binary image, the first parameter is the input image, the second parameter is the threshold value, which is used to specify the threshold for the binary thresholding operation. In this example, we will set the threshold value to 125, which means that all pixel values that are greater than or equal to 125 will be set to 255 (white), and all pixel values that are less than 125 will be set to 0 (black). The third parameter is the maximum value, which is used to specify the value that will be assigned to pixel values that are greater than or equal to the threshold value. In this example, we will set the maximum value to 255, which means that all pixel values that are greater than or equal to 125 will be set to 255 (white). The fourth parameter is the thresholding type, which is used to specify how the thresholding operation will be applied. In this example, we will set the thresholding type to THRESH_BINARY, which means that we will apply a binary thresholding operation to the image.
cv.imshow('Thresholded', thresh)


# Contours
contours, hierarchies = cv.findContours(canny, cv.RETR_LIST, cv.CHAIN_APPROX_SIMPLE) # find the contours in the Canny edge detected image, the first parameter is the input image, the second parameter is the contour retrieval mode, which is used to specify how the contours will be retrieved. In this example, we will set the contour retrieval mode to RETR_LIST, which means that all contours will be retrieved and stored in a list. The third parameter is the contour approximation method, which is used to specify how the contours will be approximated. In this example, we will set the contour approximation method to CHAIN_APPROX_SIMPLE, which means that only the endpoints of the contours will be stored in the list of contours. The findContours function returns a list of contours and a list of hierarchies, where each contour is represented as a list of points that define the contour.
# hierarchies is a list of the same length as the number of contours, where each element in the hierarchies list is a list of four values that represent the hierarchy of the contour. The first value is the index of the next contour at the same hierarchical level, the second value is the index of the previous contour at the same hierarchical level, the third value is the index of the first child contour, and the fourth value is the index of the parent contour. The hierarchy information can be used to determine the relationship between contours, such as whether a contour is a child of another contour or whether a contour is a parent of another contour.
# For example, if we have a contour that is a child of another contour, we can use the hierarchy information to determine the relationship between the two contours and how they are nested within each other. The hierarchy information can also be used to filter out contours based on their hierarchical level, such as only keeping contours that are at a certain hierarchical level or only keeping contours that are children of a certain contour.
print(f'{len(contours)} contours found!') # print the number of contours found in the image

cv.drawContours(blank, contours, -1, (0, 0, 255), 1) # draw the contours on the blank image, the first parameter is the input image, the second parameter is the list of contours, the third parameter is the contour index, which is used to specify which contour to draw. If the contour index is set to -1, all contours will be drawn. The fourth parameter is the color of the contours, which is specified as a tuple of BGR values. In this example, we will set the color to (0, 0, 255), which means that the contours will be drawn in blue. The fifth parameter is the thickness of the contours, which is used to specify how thick the contours will be drawn. In this example, we will set the thickness to 1, which means that the contours will be drawn with a thickness of 1 pixel.
cv.imshow('Contours Drawn', blank)

cv.waitKey(0)